name: DeploySimpleWorkflow
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ github.run_id }}.zip
          files: ./
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build] 
    steps:
     - uses: azure/login@v1
       with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
     - name: Get publish Profile
       id: laapp
       uses: azure/powershell@v1
       with:
         inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ secrets.RG_LA }} `
              -Name ${{ secrets.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
         azPSVersion: latest

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: Deploy to Azure Logic App
       uses: Azure/functions-action@v1
       id: la
       with:
        app-name: ${{secrets.RG_LA}}
        package: build-art/${{ github.run_id }}.zip
        publish-profile: ${{steps.laapp.outputs.profile}}
